$engine: 3
$onesync: on
$minFxVersion: 7290
name: ND Core
description: The official recipe for ND Core.
author: Andyyy and Willow-6855

tasks: 
  #  Download Base Files
  - action: download_github
    src: https://github.com/ND-Framework/txadmin-recipe
    ref: main
    dest: ./tmp/

  - action: move_path
    src: ./tmp/server.cfg
    dest: ./server.cfg

  - action: move_path
    src: ./tmp/logo.png
    dest: ./logo.png

  # Prepare Database
  - action: connect_database
  - action: query_database
    file: ./tmp/characters.sql
    
  - action: query_database
    file: ./tmp/vehicles.sql
    
  # Download default CFX resources
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: master
    subpath: resources
    dest: ./resources/[default]
    
  # Download Resources
  - action: download_file
    url: https://github.com/ND-Framework/ND_Core/releases/latest/download/ND_Core.zip
    path: ./tmp/ND_core.zip
  - action: unzip
    src: ./tmp/ND_core.zip
    dest: ./resources/[nd]

  - action: download_file
    url: https://github.com/ND-Framework/ND_Dealership/releases/latest/download/ND_Dealership.zip
    path: ./tmp/ND_Dealership.zip
  - action: unzip
    src: ./tmp/ND_Dealership.zip
    dest: ./resources/[nd]
    ###
  - action: download_file
    url: https://github.com/ND-Framework/ND_Nitro/releases/latest/download/ND_Nitro.zip
    path: ./tmp/ND_Nitro.zip
  - action: unzip
    src: ./tmp/ND_Nitro.zip
    dest: ./resources/[nd]
    
  - action: download_file
    url: https://github.com/ND-Framework/ND_Characters/releases/latest/download/ND_Characters.zip
    path: ./tmp/ND_Characters.zip
  - action: unzip
    src: ./tmp/ND_Characters.zip
    dest: ./resources/[nd]

  - action: download_file
    url: https://github.com/ND-Framework/ND_Status/releases/latest/download/ND_Status.zip
    path: ./tmp/ND_Status.zip
  - action: unzip
    src: ./tmp/ND_Status.zip
    dest: ./resources/[nd]
    
  - action: download_file
    url: https://github.com/ND-Framework/ND_Banking/releases/latest/download/ND_Banking.zip
    path: ./tmp/ND_Banking.zip
  - action: unzip
    src: ./tmp/ND_Banking.zip
    dest: ./resources/[nd]

  - action: download_file
    url: https://github.com/overextended/ox_lib/releases/latest/download/ox_lib.zip
    path: ./tmp/ox_lib.zip
  - action: unzip
    src: ./tmp/ox_lib.zip
    dest: ./resources/[ox]

  - action: download_file
    url: https://github.com/overextended/oxmysql/releases/latest/download/oxmysql.zip
    path: ./tmp/oxmysql.zip
  - action: unzip
    src: ./tmp/oxmysql.zip
    dest: ./resources/[ox]
 
 - action: download_file
    url: https://github.com/overextended/ox_target/releases/latest/download/ox_target.zip
    path: ./tmp/ox_target.zip
  - action: unzip
    src: ./tmp/ox_target.zip
    dest: ./resources/[ox]

 - action: download_file
    url: https://github.com/overextended/ox_doorlock/releases/latest/download/ox_doorlock.zip
    path: ./tmp/ox_doorlock.zip
  - action: unzip
    src: ./tmp/ox_doorlock.zip
    dest: ./resources/[ox]
    
  # Clean up
  - action: remove_path
    path: ./tmp
