$engine: 3
$onesync: on
$minFxVersion: 7290
name: ND_Core
description: The official recipe for ND_Core.
author: Andyyy

tasks: 
  # Download default CFX resources
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: master
    subpath: resources
    dest: ./resources/[default]

  # Download server.cfg
  - action: download_file
    url: https://raw.githubusercontent.com/ND-Framework/txadmin-recipe/main/server.cfg
    path: ./server.cfg

  # Download logo
  - action: download_file
    url: https://github.com/ND-Framework/txadmin-recipe/blob/main/logo.png
    path: ./logo.png
    
  # Download ndcore.cfg
  - action: download_file
    url: https://raw.githubusercontent.com/ND-Framework/txadmin-recipe/main/ndcore.cfg
    path: ./ndcore.cfg
    
  # Download resources.cfg
  - action: download_file
    url: https://raw.githubusercontent.com/ND-Framework/txadmin-recipe/main/resources.cfg
    path: ./ndcore.cfg

  - action: download_file
    url: https://github.com/ND-Framework/ND_Core/releases/download/v2.1.1/ND_Core.zip
    path: ./tmp/ox_core.zip
  - action: unzip
    src: ./tmp/ox_core.zip
    dest: ./resources/[ox]
